language: cpp

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_USER
    - secure: "uckk46eJtAqmbWVLi25rJFxdFK7B58LZ0aw8PQsFAUpi+yJDaQEiT8usSJpZaWFQt+m03D7s9+TWuVfl1OIxYv7uqQ7aLGPNP4cvMssm5ZSgS5gErTCgB/kXjgjVjN8CALQ0b+jkepCVImqvc3YYC+Zp9s6kL6viYYMYZlDcWV2c86qSY21UzMxpKoEvY6Hp0YA/SdJLpejwSlZyNVnmFv4neHAohVhiPc4vyhe6Z5kMdryZbuGqKsdpt071vDqdbKgsKDlfU3oqPU7jONDcVpj6uk9MkSzWEsLhdSuK90FSkVKCBbl4tGr8R9gNyLNEPjwv2bTd+nUaQg2OzUxLwjnAIruwi0ZGTttv/9H2Egkjxcn3/8WNekUu4j5WqNwT79Gd8KIxx8mEZ3WBPEHPZIi+Bv0QCMf435Lxgw+YUTpa+HwfOhAOAodu3C1QVl5ezC44qiq8NF2H+ufkwNNJ90Yd0RkXRqsRjlvJXkpVZvXAeYmrCT27z+VRyzAi/XplZLAabJ4GgGHQ834Np88uyzZdK6pgJLuezjYd9aKrtqtV5iWygYzF1c165DPatWVVu8u/CCDjS0S+KtwdToV+j/eJN/88f5tzvhV3M/Wr+TzMFvuE4+uB3aRhOmNEgbKI574vTEOTS5B/W8R87M0PPIk5EYAvMcllvKTQ8dRwkGw="
    # DEPLOY_HOST
    - secure: "AXVEAZxVEELX868xdgg9DDwj8qx50jSFu5dhZuK3WdEBzNsIr6pkA+6wply8X4m3jscj9+WKh4SJLy9gquXkcXNQLBO3I32mlV7n99OUgTnrak8T0EPPr/eaYozxOBApW1HoDOd646TO53mpPqi65UdABP/DTnAhjnoT5gLU9AMKLsFk2+HrZVD0wKm3B+ezL7FSm/uIPA3MMY1y7MvzysDX9PWElXS+pLCTze36HZ3G74lfXDBMA8U/ZZ02jTzrZLi0dZg98pI6iQMoYjsSGZpvGBiCIQqlr9+y3dLHhLDEyzyyaco9dDqD1084iJMai+n7dLn1AfZGqKwNrwkrdqO7nsQaleYWSK7H1+eAVJvgNsFOPpnPYW9urGthusI80IALabpuQehCaxUU5bk7Rj8gRWnviIuX3gTQ8eJCpe45KvTn6IVH90MgskmX1YahQAtrMGes47fSAwHO3kwCNmJGB5BuNmypG7D/cOoS4mNoc0ifkU9OC/Y8gH2PuNy6EuLW632MCNj9/LHrke06fD0UhkNRyy1+w1XAWIjVcP0Byuw+pAE+KavWD1wQ4TVhzIm2gpa42Lt+NLMy+QApc01afXasQZPYA7PipMIc30VlHFcvXWthWsuG2oCXCTpphSm1E3mkqKtceSSOvLCuD2rxcO7nC7QBhw9q2tIu3Jk="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

deploy:
  - provider: script
    script: .travis/deploy.sh build/artifacts/cmakeshared-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"
  - provider: script
    script: .travis/deploy.sh build/artifacts/cmakeshared-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
