name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    - name: build
      run: |
        cd build
        make -j
        make install
    - name: package
      if: "github.event_name == 'push'"
      run: |
        cd build
        mkdir -p artifacts
        tar czf artifacts/cmake-shared-artifacts.tar.gz -T install_manifest.txt
    - name: archive result
      if: "github.event_name == 'push'"
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: build/artifacts
