name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    - name: build
      run: |
        cd build
        make -j
        make install
    - name: test
      run: |
        cd build
        make test
    - name: package
      run: |
        cd build
        mkdir -p artifacts
        tar czf artifacts/cmakeshared-artifacts.tar.gz -T install_manifest.txt
    - name: archive result
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: build/artifacts
